language: python
dist: xenial
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
 - python setup.py install
 - pip install -r test_reqs.txt
script:
 - python setup.py flake8
 - python commonmark/tests/unit_tests.py
 - python setup.py test
 - cmark commonmark/tests/test.md
 - cmark commonmark/tests/test.md -a
 - cmark commonmark/tests/test.md -aj
